language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install python-coveralls
script:
  - ./test.sh
after_success:
  - coveralls
